name: SmpEasy
version: '${project.version}'
main: xyz.karlito1501.smpeasy.SmpEasy
api-version: 1.18
authors: [ karlo292, 3ue ]
description: SmpCore the best core plugin for the SMP beginners aka SMP creators that want their server to have good plugin with lots and lots of commands needed for a SMP or regular servers etc Hope you enjoy it! Also don't forget that were adding a Premium version of the plugin with more commands and it will be fully customizable!
website: karlito1501.xyz
